# This pipeline will:
# - Check if container already exists, if not it will create it.
# 
#
# The following variables need to be provided to the pipeline:
#
# - subscriptionId           : Subscription Id.
# - storage-account          : Name for Storage account.
# - source-container         : Name for source container.
# - source-blob-os           : Name for source blob containing OS.
# - source-blob-data         : Name for source blob containing data.
# - dest-container           : Name for destination container.
# - dest-blob-os             : Name for destination blob containing OS.
# - dest-blob-data           : Name for destination blob containing data.
#
# Pipeline are used with User assigned managed identity
#
# This pipeline also expects an Azure (Resource Manager) service connection in Azure DevOps with the name 'connection_snapshottestsa', using Workload Identity federation (manual). This service connection must have been set up in the Project Settings.


trigger: none
pr: none

pool:
  name: easec-pool
  
variables:
- group: variable_iScaleArchive

stages:
- stage: Delete_blobs_and_container
  jobs:
  - job:
    steps:
     - task: AzureCLI@2
       inputs:
         azureSubscription: 'connection_snapshottestsa'
         scriptType: pscore
         scriptLocation: inlineScript
         inlineScript: |
          $Env:AZCOPY_AUTO_LOGIN_TYPE="MSI"
          $Env:AZCOPY_MSI_CLIENT_ID="$(idCLient)"
          az storage blob delete-batch --source "$(dest-container)" --account-name "$(storage-account)" --auth-mode login
          az storage container delete --account-name "$(storage-account)" --auth-mode login --name "$(dest-container)"
