# This pipeline will:
# - Check if container already exists, if not it will create it.
# - Rehydrate archived snapshot files, from Archived to Hot.
# 
#
# The following variables need to be provided to the pipeline:
#
# - subscriptionId           : Subscription Id.
# - storage-account          : Name for Storage account.
# - source-container         : Name for source container.
# - source-blob-os           : Name for source blob containing OS.
# - source-blob-data         : Name for source blob containing data.
# - dest-container           : Name for destination container.
# - dest-blob-os             : Name for destination blob containing OS.
# - dest-blob-data           : Name for destination blob containing data.
#
# Pipeline are used with User assigned managed identity
#
# This pipeline also expects an Azure (Resource Manager) service connection in Azure DevOps with the name 'connection_snapshottestsa', using Workload Identity federation (manual). This service connection must have been set up in the Project Settings.


trigger: none
pr: none

pool:
  name: easec-pool
  
variables:
  storage-account: snapshottestsa
  subscriptionId: "0ac447d7-fbc3-4d3d-84d4-37bb9a71e089"
  source-container: "iscala-archive"
  source-blob-os: "easec-vm_OsDisk_1_snap.vhd"
  source-blob-data: "easec-vm_DataDisk_1_snap.vhd"
  dest-container: "snapshot"
  dest-blob-os: "easec-vm_OsDisk_1_snap.vhd"
  dest-blob-data: "easec-vm_DataDisk_1_snap.vhd"

stages:
- stage: check_container_exist
  jobs:
  - job:
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'connection_snapshottestsa'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            exist=$(az storage container exists --account-name "$(storage-account)" --auth-mode login --name "$(dest-container)" --query [exists] -o tsv)
            echo $exist
            if [ "$exist" = "true" ]; then
              echo "Container exist"
            else
              echo "Container does´nt exist"
              az storage container create --name "$(dest-container)" --account-name "$(storage-account)" --auth-mode login
            fi
          
